/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#fbb795",
        "on-primary": "#4e250d",
        "inverse-surface": "#e2e2e8",
        "surface-container-highest": "#333539",
        "surface-warm": "#242830",
        "on-secondary-container": "#aab6cc",
        "on-primary-fixed-variant": "#693b21",
        "tertiary": "#95d1d6",
        "on-tertiary-fixed-variant": "#054f54",
        "on-primary-fixed": "#341100",
        "outline-variant": "#52443d",
        "inverse-on-surface": "#2f3035",
        "on-tertiary": "#00363a",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#bcc7dd",
        "surface-dim": "#111317",
        "on-surface-variant": "#d7c2ba",
        "secondary-fixed": "#d8e3fa",
        "status-success": "#2D6A4F",
        "outline": "#9f8d85",
        "primary-fixed": "#ffdbcb",
        "primary-container": "#cc8e6e",
        "on-secondary": "#263142",
        "tertiary-fixed-dim": "#95d1d6",
        "surface-base": "#0F1115",
        "status-warning": "#B7791F",
        "on-secondary-fixed": "#111c2c",
        "slate-muted": "#718096",
        "tertiary-fixed": "#b1edf2",
        "tertiary-container": "#6ba6ab",
        "surface-container-lowest": "#0c0e12",
        "surface-elevated": "#1A1D23",
        "on-error": "#690005",
        "surface": "#111317",
        "status-error": "#9B2C2C",
        "secondary-container": "#3c475a",
        "on-background": "#e2e2e8",
        "primary-fixed-dim": "#fbb795",
        "background": "#111317",
        "surface-container": "#1e2024",
        "on-tertiary-fixed": "#002022",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-high": "#282a2e",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-bright": "#37393e",
        "primary": "#fbb795",
        "copper-accent": "#CC8E6E",
        "inverse-primary": "#855236",
        "on-surface": "#e2e2e8",
        "on-primary-container": "#532810",
        "surface-container-low": "#1a1c20",
        "secondary": "#bcc7dd",
        "on-tertiary-container": "#003a3e",
        "surface-variant": "#333539"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-lg": "32px",
        "unit": "4px",
        "margin": "32px",
        "stack-md": "16px",
        "gutter": "24px",
        "container-max": "1440px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "display-lg": ["Spline Sans"],
        "body-sm": ["Inter"],
        "tech-code": ["Sora"],
        "headline-lg": ["Spline Sans"],
        "body-lg": ["Inter"],
        "headline-md": ["Spline Sans"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Spline Sans"],
        "label-md": ["Sora"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "tech-code": ["12px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "label-md": ["13px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
